version: '3'

services:
    
  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_1
      - service_2
      - service_3
    links :
      - service_1
      - service_2
      - service_3 
    

  service_1:
    build: ./service_1
    image : proma0504/service_1
    # container_name: userservice
    restart: unless-stopped

  service_2:
    build: ./service_2
    image : proma0504/service_2
    # container_name: userservice
    restart: unless-stopped

  service_3 :
    build: ./service_3
    image : proma0504/service_3
    # container_name: userservice
    restart: unless-stopped
    depends_on:
      - service_2


  